server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/patent_system?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB

#配置日志
logging:
  #配置日志文件路径
  file: public\manager.log
mybatis:
  typeAliasesPackage: com.suixingpay.patent.pojo
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

visualpath: http://127.0.0.1:8080/

patentNeedCheckStatus: 3

