server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/patent_system?characterEncoding=UTF-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
#配置日志
logging:
  #配置日志文件路径
  file: log\manager.log