server:
  port: 8080


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.suixingpay.patent.pojo

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/patent_system?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

#配置日志
logging:
  #配置日志文件路径
  file: log\manager.log


