server:
  port: 8080



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/patent_system?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

#配置日志
logging:
  #配置日志文件路径
  file: log\manager.log

mybatis:
  typeAliasesPackage: com.suixingpay.patent.pojo
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
